/*
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl.ui.tests;

import com.google.inject.Injector;
import es.uam.sara.tfg.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class JRulesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("es.uam.sara.tfg.dsl.JRules");
	}

}
