/**
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl.scoping;

import es.uam.sara.tfg.dsl.scoping.AbstractJRuleScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class JRuleScopeProvider extends AbstractJRuleScopeProvider {
}
