/**
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl;

import es.uam.sara.tfg.dsl.JRuleStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JRuleStandaloneSetup extends JRuleStandaloneSetupGenerated {
  public static void doSetup() {
    JRuleStandaloneSetup _jRuleStandaloneSetup = new JRuleStandaloneSetup();
    _jRuleStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
