/**
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl;

import es.uam.sara.tfg.dsl.AbstractJRuleRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JRuleRuntimeModule extends AbstractJRuleRuntimeModule {
}
