/*
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JRulesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/uam/sara/tfg/dsl/parser/antlr/internal/InternalJRules.tokens");
	}
}
