/*
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJRulesScopeProvider extends DelegatingScopeProvider {
}
