/**
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl.validation;

import es.uam.sara.tfg.dsl.validation.AbstractJRuleValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JRuleValidator extends AbstractJRuleValidator {
}
